# Generated by Django 3.2 on 2021-05-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=30),
        ),
    ]
